title = "Nick Del Nano's blog"
theme = "hugo-dusk"
license = "MIT"
licenselink = "https://github.com/gyorb/hugo-dusk/blob/master/LICENSE.md"
description = "A minimalistic dark responsive theme."
homepage = "https://github.com/gyorb/hugo-dusk"
tags = ["blog", "responsive", "google analytics", "disqus", "utterances", "syntax highlighting", "custom themes", "minimal", "minimalist", "clean", "dark"]
features = ["blog"]
min_version = "0.133.0"

[author]
  name = "Nick Del Nano"

[markup]
  [markup.highlight]
    style = "native" 

[params]
theme_colors = "default-dark"
